export const PaymentOrderRecurPaymentRequest = {
  paymentorder: {
    operation: 'Recur',
    recurrenceToken: '09ccd29a-7c4f-4752-9396-12100cbfecce',
    currency: 'SEK',
    amount: 1000,
    vatAmount: 250,
    description: 'Test Purchase',
    userAgent: 'Mozilla/5.0...',
    language: 'sv-SE',
    urls: {
      callbackUrl: 'https://example.com/callback',
    },
    payeeInfo: {
      payeeId: '5cabf558-5283-482f-b252-4d58e06f6f3b',
      payeeReference: 'CD1234',
      payeeName: 'Merchant1',
      productCategory: 'A123',
      orderReference: 'or-12456',
      subsite: 'Subsite1',
    },
    orderItems: [
      {
        reference: 'P1',
        name: 'Product1',
        type: 'PRODUCT',
        class: 'ProductGroup1',
        itemUrl: 'https://example.com/shop/id=123',
        imageUrl: 'https://example.com/product1.jpg',
        description: 'Product 1 description',
        discountDescription: 'Volume discount',
        quantity: 4,
        quantityUnit: 'pcs',
        unitPrice: 300,
        discountPrice: 200,
        vatPercent: 2500,
        amount: 1000,
        vatAmount: 250,
      },
    ],
  },
};
