//TODO: Figure out how to convert this from C# to TS
export enum LinkRelation {
    UpdatePaymentOrderUpdateOrder = PaymentOrderResourceOperations.UpdatePaymentOrderUpdateOrder,
    CreatePaymentOrderCapture = PaymentOrderResourceOperations.CreatePaymentOrderCapture,
    CreatePaymentOrderCancel = PaymentOrderResourceOperations.CreatePaymentOrderCancel,
    UpdateAbort = PaymentOrderResourceOperations.UpdatePaymentOrderAbort,
    CreatePaymentOrderReversal = PaymentOrderResourceOperations.CreatePaymentOrderReversal,
    View = PaymentOrderResourceOperations.ViewPaymentOrder,
    RedirectPaymentOrder = PaymentOrderResourceOperations.RedirectPaymentOrder,
    RedirectVerification = PaymentOrderResourceOperations.RedirectVerification,
    ViewConsumerIdentification = ConsumerResourceOperations.ViewConsumerIdentification,
    RedirectConsumerIdentification = ConsumerResourceOperations.RedirectConsumerIdentification,
    CreateCancellation = PaymentResourceOperations.CreateCancellation,
    CreateCapture = PaymentResourceOperations.CreateCapture,
    CreateReversal = PaymentResourceOperations.CreateReversal,
    PaidPaymentOrder = PaymentOrderResourceOperations.PaidPaymentOrder,
    PaidPayment = PaymentResourceOperations.PaidPayment,
    UpdatePaymentAbort = PaymentResourceOperations.UpdatePaymentAbort,
    ViewAuthorization = PaymentResourceOperations.ViewAuthorization,
    RedirectAuthorization = PaymentResourceOperations.RedirectAuthorization,
    CreateSale = PaymentResourceOperations.CreateSale,
    RedirectSale = PaymentResourceOperations.RedirectSale,
    ViewSales = PaymentResourceOperations.ViewSale,
    AbortedPayment = PaymentResourceOperations.AbortedPayment,
    AbortedPaymentOrder = PaymentOrderResourceOperations.AbortedPaymentOrder,
    RedirectAppSwish = PaymentResourceOperations.RedirectAppSwish,
    ViewPayment = PaymentResourceOperations.ViewPayment,
    ViewVerification = PaymentResourceOperations.ViewVerification,
    UpdateAuthorizationOverchargedamount = PaymentResourceOperations.UpdateAuthorizationOverchargedAmount,
    CreateApprovedLegalAddress = PaymentResourceOperations.CreateApprovedLegalAddress,
    CreateAuthorization = PaymentResourceOperations.CreateAuthorization,
    DirectAuthorization = PaymentResourceOperations.DirectAuthorization,
}